name: 'Terraform GitHub Actions'
on:
  - pull_request
jobs:
  terraform:
    name: 'tflint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: tflint
        id: tflint
        run: |
          pwd
          ls
          curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          output=""
          for d in $(find ./ -type d) ;do
            section=$(tflint -f json --force --config=./.tflint.hcl $d |jq -c '.issues[] | "ISSUE FOUND: (\(.rule.name)) in \(.range.filename) line \(.range.start.line) - \(.range.end.line)¡"')
            output+=$(if [ ${#section} -gt 1 ] ; then echo "***ISSUE(S) FOUND IN ${d}***:¡${section}¢"; fi);
          done
          output=$( echo $output | sed -e 's/"//g' )
          IFS='¢' read -r -a array <<< "$output"
          if [ ${#array[@]} -gt 0 ]; then echo '::set-output name=COMMENT::true'; else echo '::set-output name=COMMENT::false'; fi
          for i in "${array[@]}"
            do
              IFS='¡' read -r -a comment_sections <<< "$i"
              echo "${comment_sections[0]}" >> .github/workflows/comment.md
              echo "\`\`\`" >> .github/workflows/comment.md
              for p in "${comment_sections[@]:1}"
                do
                  echo $p >> .github/workflows/comment.md
                done
              echo -e "\`\`\` \n" >> .github/workflows/comment.md
            done
      - name: Add checkout commands
        uses: harupy/comment-on-pr@master
        if: steps.tflint.outputs.COMMENT == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.REPOCOMMIT }}
        with:
          filename: comment.md
      - name: Fail job if comments
        if: steps.tflint.outputs.COMMENT == 'true'
          run: exit 1
      - name: Print success message if we don't exit at the last step
        run: echo success!
